<?php

/**
 * 数据库队列任务类
 * User: zhenxiaotao
 * Date: 2016/11/21
 * Time: 17:30
 */
namespace shmilyzxt\queue\jobs;

use shmilyzxt\queue\base\Job;
use shmilyzxt\queue\base\JobInterface;
use yii\helpers\Json;

class DatabaseJob extends Job implements JobInterface
{
    /**
     * 数据库记录对象
     * @var
     */
    public $job;

    /**
     * DatabaseQueue实例
     * @var
     */
    public $dbQueue;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->instance->attempts = $this->instance->attempts + 1;
    }

    public function fire()
    {
        $this->resolveAndFire(Json::decode($this->getRawBody()));
    }

    public function attempts()
    {
        return $this->instance->attempts;
    }

    public function getRawBody()
    {
        return $this->instance->payload;
    }

    public function getJobId(){
        return $this->instance->id;
    }

    public function relaese($delay=0)
    {
        parent::release($delay);
        $this->delete();
        $this->dbQueue->release($this->queue,$this->instance,$delay);
    }

    public function failed()
    {
        // TODO: Implement failed() method.
    }

    public function delete()
    {
        parent::delete();
        $this->dbQueue->deleteReserved($this->queue,$this->instance->id);
    }
}